fastlane_version "2.30.2"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    bundle_install
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :devbuild do
    gym(export_method: "development")
  end

  desc "Distribute to Beta"
  lane :upload_beta do
    crashlytics(
      api_token: ENV["beta_api_token"],
      build_secret: ENV["beta_build_secret"],
      groups: 'testers'
    )
end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
